image: Visual Studio 2017
platform: x64
configuration: Release
clone_folder: C:\Projects\bsfExamples

build_script:
  - cmd: set INSTALL_DIR=C:/Projects/bsfExamples/install/Release
  - cmd: mkdir "%INSTALL_DIR%"
  - cmd: mkdir Build
  - cmd: cd Build
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:STRING=%INSTALL_DIR% ..
  - cmd: cmake --build ./ --config Release